#!/usr/bin/env python3
import json,csv
from pathlib import Path
R=Path(__file__).resolve().parents[1]
# Priority is an engineering sequencing hypothesis, not measured market demand.
F=[
('AB-MON','Monitoring and inspection','Foundation','All selected industrial segments','Common data acquisition, calibration, event logs and inspection records','Buy industrial sensors and DAQ; develop software and fixtures','Measurement uncertainty, mounting repeatability, data quality, false alarms','Do not put AI in the safety loop. Start advisory.','dellner-bubenzer;svendborg;emg'),
('AB-DR','DIN interface drum brakes','Core platform','Factory cranes, industrial winches and material handling','Base, levers, springs, shoes and adjustments across controlled size variants','Design assembly; outsource metalwork; buy thruster and lining initially','Holding/dynamic torque, release time, thermal duty, wear, fatigue','Approve one real duty envelope before selecting the first sizes.','galvi;sibre;dellner-bubenzer'),
('AB-DC','Spring-applied disc calipers','Core platform','Conveyors, winches, cranes and heavy industry','Caliper architecture, lining retention, mounting and spring arrangements','Design assembly; outsource bodies; buy hydraulic actuation parts','Contact balance, torque, thermal growth, release clearance, seal/spring life','Parallel requirements work; separate lead needed for parallel detailed design.','twiflex;stromag;svendborg;galvi;sibre'),
('AB-SP','Service parts and friction kits','Alongside core','Installed AI Braking product families','Shoes, pads, bushes, pins, seals and adjustment kits tied to revisions','Buy characterized lining compound; outsource controlled parts','Friction-pair validation, retention, lot consistency and fit','Start with our own assemblies; competitor compatibility requires separate assessment.','galvi;mondel;svendborg'),
('AB-ROT','Drums, discs and hubs','Alongside core','Both brake platforms','Machined rotating interfaces and documented material variants','Outsource casting/forging/machining to approved specifications','Thermal cycles, surface finish, runout, balance, speed and hub strength','Keep each friction pair and rotor material configuration identifiable.','galvi;mondel;twiflex;svendborg'),
('AB-AIST','AISE/AIST interface shoe brakes','Expansion','Steel mills, ports and export replacement projects','Reuse proven mechanisms where requirements permit; distinct interface families','Design adaptations; outsource metalwork; buy actuation','Imperial interfaces, severity of duty, endurance and machine qualification','Not just a unit conversion from DIN.','galvi;mondel'),
('AB-ACT','Electrohydraulic thrusters','Expansion','Drum and thruster-operated disc brakes','Motor, pump, piston, seals and force/stroke variants','Buy initially; evaluate proprietary design after performance and cost studies','Force-stroke-time curves, temperature, orientation, leakage and endurance','Treat as its own development programme, including electrical requirements.','emg;galvi;dellner-bubenzer'),
('AB-HPU','Hydraulic power units','Expansion','Hydraulically released calipers and emergency brakes','Reservoir, pump, valves, filtration, sensing and manifolds','Integrate purchased qualified components before custom hydraulic development','Release/application transients, contamination, leakage, loss of power and pressure','Controlled braking requires system dynamics and machine interface requirements.','galvi;svendborg;stromag;dellner-bubenzer'),
('AB-COUP','Flexible and gear couplings','Expansion','Drive trains with brake drums/discs','Shared hub interfaces and modular rotating components','Buy proven couplings initially; design only against defined demand','Misalignment, torsion, balance, fatigue and lubrication','Keep coupling torque capacity distinct from braking torque.','galvi;twiflex;dellner-bubenzer'),
('AB-POS','Positive-actuated brakes','Application-led','Process machinery and controlled braking applications','Reuse selected caliper or shoe elements with distinct actuation','Buy actuator/control components; design mechanism variants','Loss-of-actuation behaviour, modulation, timing and application integration','Does not inherit spring-applied fail-safe behaviour.','galvi;twiflex;stromag'),
('AB-BUF','Industrial buffers','Separate programme','Cranes, travelling equipment and end stops','Energy absorber families selected by actual impact requirements','Initially partner with specialist energy-absorber suppliers','Impact energy, peak force, stroke, recovery, temperature and repeated impacts','Cannot qualify from brake torque tests.','galvi;sibre'),
('AB-SPEC','Storm, locking and special systems','Separate programme','Ports and specialized machinery','Rail/wheel clamps, locks, turning/locking/braking integrations','Partner first; design against signed system requirements','Wind/rail interface, static holding, fault states and system integration','Hazardous-area and personnel-transport uses need distinct qualification projects.','dellner-bubenzer;svendborg;twiflex;stromag')]
rows=[dict(code=a,name=b,stage=c,applications=d,shared_components=e,make_buy=f,validation=g,decision=h,competitors=i.split(';'),maturity='concept') for a,b,c,d,e,f,g,h,i in F]
(R/'engineering/portfolio.json').write_text(json.dumps(rows,indent=2))
with (R/'engineering/portfolio.csv').open('w') as f:
 w=csv.DictWriter(f,fieldnames=rows[0].keys());w.writeheader();w.writerows([{**r,'competitors':';'.join(r['competitors'])} for r in rows])
lines=['# AI Braking proposed product portfolio','', 'Revision 0.1 | Concept only | 7 September 2026','', 'These 12 workstreams describe a broad portfolio, not 12 finished products. Customer relevance is a hypothesis until supported by RFQs. The order favours shared engineering and test evidence; it is not a claim of market share. No torque or size ratings are assigned to AI Braking products yet.','', '## Sequencing rationale','', 'Begin common inspection/monitoring while specifying both core mechanical platforms. Service parts and rotors develop with those platforms. Buy specialist actuation and friction components first. Expand into additional interfaces and proprietary subsystems after validation. Keep impact buffers and storm/locking systems in separate test programmes.','', 'Each family below balances intended customer relevance, component reuse, supplier strategy and validation burden. Supplier availability and economics remain unverified until quotations arrive.','']
for x in rows:
 lines += [f"## {x['code']} - {x['name']}",f"Stage: {x['stage']} | Maturity: concept",'',f"Intended applications: {x['applications']}.",'',f"Reuse opportunity: {x['shared_components']}.",'',f"Make/buy: {x['make_buy']}.",'',f"Required evidence: {x['validation']}.",'',x['decision'],'',f"Competitor references: {', '.join(x['competitors'])}. See the manufacturer collection reports for source URLs and gaps.",'']
(R/'reports/PRODUCT-PORTFOLIO.md').write_text('\n'.join(lines))
